experiment_type: neumf
alias: neumf_factor8neg4
num_epoch: 100
batch_size: 1024
optimizer: adam
adam_lr: 0.001
num_users: 6040
num_items: 3706
latent_dim_mf: 8
latent_dim_mlp: 8
num_negative: 4
layers: [16, 64, 32, 16, 8]  # layers[0] is the concat of latent user vector & latent item vector
l2_regularization: 0.0000001
weight_init_gaussian: true
use_cuda: true
device_id: 0
pretrain: false
pretrain_mf: checkpoints/gmf_factor8neg4_Epoch100_HR0.6391_NDCG0.2852.model
pretrain_mlp: checkpoints/mlp_factor8neg4_Epoch100_HR0.5606_NDCG0.2463.model
model_dir: checkpoints/{}_Epoch{}_HR{:.4f}_NDCG{:.4f}.model
